### ISSUE TITLE
Include directories are not updated automatically (CMake Compilation DB)

### ISSUE THREAD

**Issue by inxksp** [15knots/cmake4eclipse#193]
In the project tree, icludes directories are updated only after closing and opening the project, update (F5) has no effect

**Comment by 15knots** [comment]
fixed in ad670ec26eafa260eeb53887656823de7d9748a1

**Comment by ksrp1984** [comment]
> fixed in [ad670ec](https://github.com/15knots/cmake4eclipse/commit/ad670ec26eafa260eeb53887656823de7d9748a1)

The problem is back: latest version of the plugin
Tested on Windows and Linux

**Comment by 15knots** [comment]
Did you update CDT too or not? Just to make shure CDT isn't the culprit.

**Comment by ksrp1984** [comment]
> Did you update CDT too or not? Just to make shure CDT isn't the culprit.

![image](https://github.com/user-attachments/assets/98450d24-f056-432b-b491-fa27288db28f)

**Comment by inxksp** [comment]
> isn't the culprit.
It seems the problem only appears during the first compilation.
Check:
1. Delete directory _build
2. Close project
3. Close Eclipse
4. Open Eclipse and project
5. Run compilation
