### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser does not detect compiler-built-in macros and include paths

### ISSUE THREAD

**Issue by pepe82sh** [15knots/cmake4eclipse#79]
**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description

When using the `CMAKE_EXPORT_COMPILE_COMMANDS Parser` it seems to parse `-D` flags for macros, but does not start the compiler to get the predefined macros as `CDT GCC Built-in Compiler Settings [...]` would do.

### What is the expected behavior?

The compiler in `compile_commands.json` should be used to get the predefined macros by starting the compiler on an empty file with the given settings, plus `-E -P -dM` flags.

### What behavior are you observing?
The command line in `compile_commands.json` is parsed for `-D` flags, which will find manually defined macros, but not predefined macros.

Developing embedded systems I do heavily depend on predefined macros for specific c/c++ builds. Not having those predefined macros marks lots of my code invalid, as eclipse does not know about these macros I test for.

## Useful Information
cmake4eclipse version: 1.11.0.201802241905
Which OS do you use: MS Windows 10
Cmake version: 3.11.0

**Comment by pepe82sh** [comment]
This could also be a fix for #74. Using `-E -P -dM -Wp,-v` will return the include paths as well as the predefined macros. This could spare you any parsing issues of command line arguments, as the compiler will interpret them for you anyway.

**Comment by 15knots** [comment]
Simply enable the `CDT GCC Built-in Compiler Settings` Provider in your project.
The compiler flags you suggest are specific to gcc or clang only, whereas the `CMAKE_EXPORT_COMPILE_COMMANDS Parser` any C compiler (icc, cl, ...).

**Comment by 15knots** [comment]
I would implement it as an additional language settings provider to not over-complicate the existing one.

**Comment by pepe82sh** [comment]
Sorry for replying this late. I have been offline for a week. Unfortunately I have no ICC available, but I'll answer as best as I can.

ICC:
[**-dD**](https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-dd-qdd) and [**-dM**](https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-dm-qdm) are both available. [Like in gcc](https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Preprocessor-Options.html#Preprocessor-Options), **-dD** appearently does not include predefined Macros. At least the output of gcc is not empty for an empty file, so I'm not sure about their definition of "predefined macro".
[According to Intel](https://software.intel.com/en-us/forums/intel-c-compiler/topic/306909) you may get all include paths using `icpc -H -c test.cpp`.

CL:
Unfortunately I can't find a feature covering what we'd need. Even worse, I have to revoke what I wrote earlier about their support of /dD or /dM. At least on my machine these options are unknown, and I can't find the source that brought me to that conclusion... Sometimes I hate "past me".

**Comment by 15knots** [comment]
ICC:
> According to Intel

 `-H` gives all include **files**, but not the include **directories**
Anyway, I'm wondering what the output looks like.

CL:
Its a preprocessor option, and maybe undocumented.
Maybe `/EP /dM` works, would you try that?

**Comment by pepe82sh** [comment]
I did try, and unfortunately got this output: `cl : Command line warning D9002 : ignoring unknown option '/dM' foo.cpp`. Searching for anything useful I stumbled upon [this thread](https://stackoverflow.com/questions/3665537/how-to-find-out-cl-exes-built-in-macros) on stack overflow. It's definitely **not** what we could use in this case, but might point out that there is no *useful* way for CL. Further down `/P` is suggested, but it does not do what we need either.

Regarding the include paths: cl.exe has a `/showIncludes` option, that prints all files included for the current compilation unit. Unfortunately I find no way to keep CL from compiling. So to get all relevant include paths, all compilation units would have to be compiled. Thats quite impractical.

**Comment by 15knots** [comment]
Am Montag, 2. Juli 2018, 09:49:42 CEST schrieb pepe82sh:
> I did try, and unfortunately got this output: `cl : Command line warning
> D9002 : ignoring unknown option '/dM' foo.cpp`. Searching for anything
> useful I stumbled upon [this
> thread](https://stackoverflow.com/questions/3665537/how-to-find-out-cl-exes
> -built-in-macros) on stack overflow. It's definitely **not** what we could
> use in this case, but might point out that there is no *useful* way for CL.

Found that, too. Definitely want I want to do.

..
> Regarding the include paths: cl.exe has a `/showIncludes` option, that
> prints all files included for the current compilation unit. Unfortunately I
> find no way to keep CL from compiling. So to get all relevant include
> paths, all compilation units would have to be compiled. Thats quite
> impractical.

What if you give cl an empty file? The plugin does the same with gcc.

-- 
Cd wrttn wtht vwls s mch trsr.

**Comment by pepe82sh** [comment]
`/showIncludes` shows you just the files included in the specific c/cpp-file. So if an empty file is given, there will be no included files. Thats why I think we'd need to run every single file, which doesn't seem practical.

**Comment by 15knots** [comment]
So far I implemented this for gcc/clang/nvcc.
Concerning `icc`, I would wait until someone requests support and comes along with the output of `icc -EP -dM`.
`cl` users should contact their vendor to ask him to implement the appropriate compiler options.

**Comment by pepe82sh** [comment]
Sounds reasonable. Thanks a lot!

**Comment by pepe82sh** [comment]
Unfortunately it doesn't seem to work for me, as the macros I expect are still not defined (I rebuilt the index of course). I'll paste a snippet of my compile_commands.json, hoping that you see something obvious.
```
{
  "directory": "D:/Projekte_SVN/MC_Resources/Conan/Packages/testfw/trunk/build/Debug",
  "command": "C:\\Users\\pepe82sh\\.conan\\data\\arm-gcc_installer\\0.1\\test\\testing\\package\\63a0febc4688d7a01222d6473010aff0bf6f2a06\\bin\\arm-none-eabi-g++.exe  -DDAVE_CE -DXMC4500_F144x1024 -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\include -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\build\\Debug\\generated_Diagnostics\\include -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\build\\Debug\\eulib_generated -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\Dave\\Dave\\Generated -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\Dave\\Libraries\\XMCLib\\inc -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\Dave\\Libraries\\CMSIS\\Include -ID:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\Dave\\Libraries\\CMSIS\\Infineon\\XMC4500_series\\Include -IC:\\Users\\m.pape\\.conan\\data\\EULIB\\0.1\\test\\testing\\package\\8b369dd7a716665ae8f2fa9be96430144817c537\\include -IC:\\Users\\m.pape\\.conan\\data\\CommonTypes\\1.2.3\\test\\testing\\package\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\\include -IC:\\Users\\m.pape\\.conan\\data\\Diagnostics\\0.1\\test\\testing\\package\\f1af256f6d39cf7e71c5dfab7893f06866e89128\\include  -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp  -fdata-sections -ffunction-sections -fmessage-length=0 -fno-rtti -Og -g -gdwarf-2   -o CMakeFiles\\testfw.dir\\src\\main.cpp.obj -c D:\\Projekte_SVN\\MC_Resources\\Conan\\Packages\\testfw\\trunk\\src\\main.cpp",
  "file": "D:/Projekte_SVN/MC_Resources/Conan/Packages/testfw/trunk/src/main.cpp"
},
```

**Comment by 15knots** [comment]
Which macros do you expect? `DAVE_CE` and `XMC4500_F144x1024`?
But the built-ins are shown in the Entries tab?

**Comment by pepe82sh** [comment]
Between others __GNUC__ should be available, but __GNUC__ seems to be the best indicator as it should always be available.

**Comment by 15knots** [comment]
Confused about: 

> Between others __GNUC__ should be available, but __GNUC__ seems to be the best indicator as it should always be available.

Did you check the 'Show built in values' toggle in the entries tab?

**Comment by pepe82sh** [comment]
> Confused about:
> 
>>  Between others GNUC should be available, but GNUC seems to be the best indicator as it should always be available.
Sorry, I see how that sentence went wrong. I just meant that `__GNUC__` is a good indicator for testing, and that it is not defined.

'Show built in values' is checked, and 'Disable Compiler-built-ins detection' is unchecked. I don't know how you detect and call the compiler, but could it be connected to the fact that the callable gcc binary is arm-none-eabi-g++.exe?

**Comment by 15knots** [comment]
> arm-none-eabi-g++.exe?
If the compiler name is not known by the plugin, you will find an INFO message about that fact.
If the compiler name is just `cc`, it is handled as MAYBE:GCC, if it is 'gcc', it is handled as GCC, but actually I did not test the latter.

**Comment by pepe82sh** [comment]
1. g++ is used for c++ builds, and gcc für c builds. So when commonly talking about gcc, the actual executable could be gcc or g++.
2. When cross compiling, the [target triplet](https://wiki.osdev.org/Target_Triplet) is used to prefix the cross compiler. In my example the triplet is arm-none-eabi, which is used for bare metal static builds without any operating system involved on the target.

So to detect gcc from its executable, the test should be:

1. Get executable name (without trailing .exe if exists)
2. Check if executable name is, or ends with, gcc or g++

That should work for the cases I am aware of. CC is quite generic, but I agree that MAYBE:GCC is a good way of handling it.

**Comment by 15knots** [comment]
Support for cross compilers is already [there](https://github.com/15knots/cmake4eclipse/blob/90b475ea7a87e90f8bb5a45558b696b22d2846fc/de.marw.cmake/src/main/java/de/marw/cmake/cdt/language/settings/providers/ParserDetection.java#L79) and known to be working.

As already stated: If the compiler name is not known by the plugin, you will find an INFO message about that fact (in the problems view).

**Comment by pepe82sh** [comment]
Sorry, got your last message totally wrong. There is no INFO message, so that’s not it. Do you have a working Test where `__GNUC__` is recognised by eclipse?

**Comment by 15knots** [comment]
Try one of the example projects: https://github.com/15knots/cmake4eclipse-sample-projects/tree/master/C-inclpaths

**Comment by 15knots** [comment]
Perhaps the Eclipse error log gives some hints?
I cannot reproduce here.

![cmake_export_compile_commands_parser](https://user-images.githubusercontent.com/11367029/42656959-3257d6a4-8621-11e8-9c9e-ee9eadb77880.png)

**Comment by pepe82sh** [comment]
I never looked closely at the entries tab... The variable shows up indeed, but the editor doesn't seem to recognize it. I did rebuild the Index multiple times to check if that is the issue. There are no Messages in the error log that seem connected either. Got the same behaviour in the test project you provided. Could you check if you see the same thing? If not it might be OS or installation related.

![grafik](https://user-images.githubusercontent.com/35840364/42676027-b5a90140-8676-11e8-8fe7-561af5ffbdb6.png)
![grafik](https://user-images.githubusercontent.com/35840364/42676060-ded3af0c-8676-11e8-9767-a0100e561e79.png)

**Comment by 15knots** [comment]
Same here. CDTWTF.
But why does the indexer recognize macros that come from the compiler command line?

**Comment by pepe82sh** [comment]
It seems as if the same issue is present regarding the include paths. The test project you provided uses

```
#include <stdio.h>
#include <stdlib.h>
```

Both are marked by eclipse as _unresolved inclusion_. If I browse the _Includes_ in the Project Explorer, I can see and open these header files. Really weird.

**Comment by 15knots** [comment]
I figured it out now: The indexer behaves differently from the entries tab. If an entry is added at source file scope (which is the case if it comes from the compiler command line), it does not consider any entries added at project scope (coming from the compiler built-ins).

SO I will have to add a separated provider for the built-ins.

**Comment by pepe82sh** [comment]
Oh wow, at least there is an explanation and it's solvable. Thank you very much for the effort!

**Comment by 15knots** [comment]
You will need to enable **both** parsers.
One picks up the stuff  from the compiler command lines in the compile_commands.json file, the other invokes the compiler and gets the includes paths from that output.

See _CMake for CDT User Guide_ in the eclipse help

**Comment by pepe82sh** [comment]
Tried that, but reinstalling eclipse and using a new workspace made the issue disappear now. So whatever it was shouldn't be your issue. Thanks again 👍
